- name: install_task
  apt:
    name: "{{ package_name }}"
    state: "{{ package_state }}"
  register: my_register
  
- name: Copy files using loops
  copy:
    src: "{{ item }}"
    dest: "/home/ansible/"
    mode: 0644
  with_fileglob:
      - "./Roles/web_server/files/*"
  notify: new_handler
  when: my_register.changed

- name: Trying Templates
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  

  
 
      

  
